{% set build = 0 %}
{% set name = "mpi4py-fft" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mpi4py/mpi4py-fft/archive/refs/tags/{{ version }}.tar.gz
  sha256: e5ffe01a31232563203c2330d691a494b7946619d78818ebc086c8a68f9319a2

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - fftw
    - setuptools
  run:
    - python
    - mpi4py
    - {{ pin_compatible('numpy') }}
    - fftw

test:
  source_files:
    - tests

about:
  home: https://github.com/mpi4py/mpi4py-fft
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Fast Fourier Transforms (FFTs) in parallel with MPI for Python
  description: |
    mpi4py-fft is a Python package for computing Fast Fourier Transforms
    (FFTs). Large arrays are distributed and communications are handled under
    the hood by MPI for Python (mpi4py).
  doc_url: https://mpi4py-fft.readthedocs.io
  dev_url: https://github.com/mpi4py/mpi4py-fft

extra:
  recipe-maintainers:
    - mikaem
    - dalcinl
