{% set build = 0 %}
{% set name = "mpi4py-fft" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bitbucket.org/mpi4py/mpi4py-fft/get/{{ version }}.tar.bz2
  sha256: a9ad8b198dc711e761dff6a839178c0d8dc07336704cdce319f149290c9498a1

build:
  number: {{ build }}
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - fftw
    - setuptools
  run:
    - python
    - mpi4py
    - {{ pin_compatible('numpy') }}
    - fftw

test:
  source_files:
    - tests

about:
  home: https://bitbucket.org/mpi4py/mpi4py-fft
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Fast Fourier Transforms (FFTs) in parallel with MPI for Python'
  description: |
    mpi4py-fft is a Python package for computing Fast Fourier Transforms
    (FFTs). Large arrays are distributed and communications are handled under
    the hood by MPI for Python (mpi4py).
  doc_url: https://mpi4py-fft.readthedocs.io
  dev_url: https://bitbucket.org/mpi4py/mpi4py-fft

extra:
  recipe-maintainers:
    - mikaem
    - dalcinl
