{% set build = 1000 %}
{% set name = "mpi4py-fft" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bitbucket.org/mpi4py/mpi4py-fft/get/{{ version }}.tar.bz2
  sha256: 888dbe1649bf3accf6e93e9f075fdfea6d7ba216a28dd1ba5b68cc5e386818b9

build:
  number: {{ build }}
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - {{ mpi }}
    - mpi4py
    - numpy
    - fftw
    - setuptools
  run:
    - python
    - {{ mpi }}
    - mpi4py
    - numpy
    - fftw

test:
  source_files:
    - tests

about:
  home: https://bitbucket.org/mpi4py/mpi4py-fft
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Fast Fourier Transforms (FFTs) in parallel with MPI for Python'
  description: |
    mpi4py-fft is a Python package for computing Fast Fourier Transforms
    (FFTs). Large arrays are distributed and communications are handled under
    the hood by MPI for Python (mpi4py).
  doc_url: https://mpi4py-fft.readthedocs.io
  dev_url: https://bitbucket.org/mpi4py/mpi4py-fft

extra:
  recipe-maintainers:
    - mikaem
