{% set build = 2 %}
{% set name = "mpi4py-fft" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mpi4py/mpi4py-fft/archive/refs/tags/{{ version }}.tar.gz
  sha256: 94ebf13a812b0593f94039cd19cbe268637acc2ac36c56c5d65a714411694ff9

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - fftw                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - fftw
  run:
    - python
    - mpi4py
    - fftw

about:
  home: https://github.com/mpi4py/mpi4py-fft
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Fast Fourier Transforms (FFTs) in parallel with MPI for Python
  description: |
    mpi4py-fft is a Python package for computing Fast Fourier Transforms
    (FFTs). Large arrays are distributed and communications are handled under
    the hood by MPI for Python (mpi4py).
  doc_url: https://mpi4py-fft.readthedocs.io
  dev_url: https://github.com/mpi4py/mpi4py-fft

extra:
  recipe-maintainers:
    - mikaem
    - dalcinl
