travis:
  secure:
    BINSTAR_TOKEN: gJ8nhfn79RLiSNVZujLX6qkadNQ++X+khg3CdAB2FnRq3gL+2JPLZ+F29dKMM1WgYcve1l675dpPGxz4aYSI9sQuoJWxgTXwk2BPtVRDIIHQZ3SI1IaH7v8HfEid2pHuTdQfx3qdI+WMVlT1fLs/sbuMHY8NHhlmY7DNPYA6CBxzGPOLzyvQilJaY0YK9X6TDvsMW9uPRj9RAcF8vgraJq7iYkhGNfOr4/ckVkv4YAR7Ucj1K8x7BmuS0hKBeNE/wpuxa+3nBTpuuRDyNhSxKxo+D3GuwA61cin8L9EYfDNKpLO7tpgpL/3zvqCSYrG4neWqhHCwI/xCc7eYa3iYA6oXHms4Jrnn04+UJfvTSKJpnAWxAG0dXD6kiSiYFxaBVHILtEeTty6XJA2Dzc0ew0Nw4lDkd5Qy9PwBkzmoW7iBM9y+SKmMAJAyzIIUjZ8puPxZwlHlhTH7z3vm361Lq1zW/zablZldaB1Vw7NRHsEtNzdGRr6+ksqbbxWhZWg1TJp2KklyqJWo6moILZka4YF4fEjXZYjbPbwDQUclbXLzWexg9a/RPmgH1ZnItENmfKFOqTgYdk3da66n114qP/h4r86iMALVLUVSjm176F8ZZQc2Z2dmrv86UTMpU6s7v9j511gpx1OdiIIU4HaUQgchp/kVLw3zjqQGY1oJpTk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
